version: '3'

services: 
  portainer:
    container_name: portainer
    image: portainer/portainer
    ports:
    - 9000:9000
    restart: always
    volumes: 
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer:/data

volumes:
  portainer:
